name: Setup

inputs:
  node-version:
    required: true
    type: string
  registry-url:
    required: false
    type: string

runs:
  using: composite
  steps:
    - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}
    - run: npm i -g pnpm
      shell: bash
    - run: pnpm i --ignore-scripts
      shell: bash
