name: Run Tests

inputs:
  node-version:
    required: true
    type: string

runs:
  using: composite
  steps:
    - uses: ./.github/actions/setup
      with:
        node-version: ${{ inputs.node-version }}
    - run: pnpm cypress install
      shell: bash
    - run: pnpm test
      shell: bash
    - name: Save Cypress output on failure
      if: ${{ failure() }}
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: cypress-output
        path: |
          cypress/screenshots/
          cypress/videos/
          cypress/downloads/
        retention-days: 7
