name: PR Verify

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  verify:
    permissions:
      contents: read
      actions: write
    uses: ./.github/workflows/verify.yml
    with:
      node-version: 24.x
