name: Publish New Release

on:
  release:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  id-token: write

env:
  NODE_VERSION: 24.x

jobs:
  verify:
    permissions:
      contents: read
      actions: write
    uses: ./.github/workflows/verify.yml
    with:
      node-version: 24.x

  publish-npm:
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: ./.github/actions/setup
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/
      - run: sudo apt-get install jq
      - run: jq ".version=\"${GITHUB_REF#refs/*/}\"" package.json > package-new.json && mv package-new.json package.json
      - run: cat package.json
      - run: pnpm publish-npm

  deploy-demo:
    needs: publish-npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: ./.github/actions/setup
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: pnpm --prefix demo i
      - run: pnpm --prefix demo i react-color-a11y@latest
      - name: Set Github identity
        run: |
          git config user.email "support+actions@github.com"
          git config user.name "github-actions-bot"
      - name: Deploy to Github Pages
        run: |
          pnpm build-demo
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d demo/build -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
