name: Verify

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string

permissions:
  contents: read

jobs:
  check-release-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/actions/check-release-package
        with:
          node-version: ${{ inputs.node-version }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/actions/lint
        with:
          node-version: ${{ inputs.node-version }}

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/actions/typecheck
        with:
          node-version: ${{ inputs.node-version }}

  run-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/actions/run-tests
        with:
          node-version: ${{ inputs.node-version }}
